export const zabbixData = [
  {
    key: 1,
    serviceName: "AMISP (MDM, SUMO, S4-WSE and Ewatch Read IT)",
    zabbix: "AMISP-DC and DR zabbix",
    ip: "172.18.8.75 & 172.19.8.75",
    dataCentre: "CTrls Mum and Hyd",
    version: "7.0.10",
    primaryTeam: "NOMC (09:30 to 18:00), Liberty Helpdesk (18:00 to 09:30)",
    resolverTeam: "Devops - Monil Jain and Anjali Bhati, DBA - Sourabh Nagpal and Abhay Samota",
    escalationTeam: "Application Team: MDM - Atol S Negi, S4-WSE - Dharam Menaria, Ewach Read IT - Devops(Abhishek Upadhyay) || DBA: Nilesh Gaur, Abhay Samota",
    technicalArchitect: "Sanjay Somani"
  },
  {
    key: 2,
    serviceName: "Liberty Online2.0",
    zabbix: "AMISP-DC and DR zabbix",
    ip: "172.18.8.75 & 172.19.8.75",
    dataCentre: "CTrls Mum and Hyd",
    version: "7.0.10",
    primaryTeam: "NOMC (09:30 to 18:00), Liberty Helpdesk (18:00 to 09:30)",
    resolverTeam: "Devops - Application Team, DBA - Sourabh Nagpal and Abhay Samota",
    escalationTeam: "Application and DB team, Gourav Kanthed",
    technicalArchitect: "Nitin Pandya"
  },

  {
    key: 3,
    serviceName: "BBCool",
    zabbix: "M&C Zabbix",
    ip: "172.16.239.12",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "6.2.9",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops",
    escalationTeam: "Devops - Ritu Awasthi, DBA - Abhay Samota and Naveen Mathur, Application Team - Deepaj Kalal",
    technicalArchitect: "Deepak Kalal"
  },
  {
    key: 4,
    serviceName: "BBCare",
    zabbix: "M&C Zabbix",
    ip: "172.16.239.12",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "6.2.9",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops",
    escalationTeam: "Devops - Anjali Bhati, DBA - Naveen Mathur, Application Team - Amit Gupta and Khushboo Kothari",
    technicalArchitect: "Puneet Khurana"
  },
  {
    key: 5,
    serviceName: "Ewatch Online",
    zabbix: "M&C Zabbix",
    ip: "172.16.239.12",
    dataCentre: "Ld8",
    version: "6.2.9",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "DevOps - Abhishek Upadhyay, Application Team -  Lokesh Tailor",
    technicalArchitect: ""
  },
  {
    key: 6,
    serviceName: "Ewatch Heat",
    zabbix: "M&C Zabbix",
    ip: "172.16.239.12",
    dataCentre: "Ld8 & Ld9",
    version: "6.2.9",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "DevOps - Abhishek Upadhyay, Application Team -  Lokesh Tailor",
    technicalArchitect: ""
  },
  {
    key: 7,
    serviceName: "Sugamlite",
    zabbix: "M&C Zabbix",
    ip: "172.16.239.12",
    dataCentre: "Ld8 & Ld9",
    version: "6.2.9",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "DevOps - Anjali Bhati, Application Team - Kiran Kumar",
    technicalArchitect: "Chenram Vijayvargiya"
  },
  {
    key: 8,
    serviceName: "Beanbag Heat",
    zabbix: "M&C Zabbix",
    ip: "172.16.239.12",
    dataCentre: "Ld8 & Ld9",
    version: "6.2.9",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "DevOps - Anjali Bhati, Sonia Jat",
    technicalArchitect: ""
  },
  {
    key: 9,
    serviceName: "Quick Sort",
    zabbix: "M&C Zabbix",
    ip: "172.16.239.12",
    dataCentre: "Ld8 & Ld9",
    version: "6.2.9",
    primaryTeam: "Smart Support",
    resolverTeam: "Smart Support",
    escalationTeam: "Application - Pankaj Keswani, DevOps - ",
    technicalArchitect: "Pankaj Keswani"
  },
  {
    key: 10,
    serviceName: "Heat Billing-Heat Esco",
    zabbix: "M&C Zabbix",
    ip: "172.16.239.12",
    dataCentre: "Ld8 & Ld9",
    version: "6.2.9",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "DevOps - Abhishek Upadhyay, Application Team -  Lokesh Tailor",
    technicalArchitect: ""
  },
  {
    key: 11,
    serviceName: "Prod DAST",
    zabbix: "M&C Zabbix",
    ip: "172.16.239.12",
    dataCentre: "Ld8 & Ld9",
    version: "6.2.9",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "Devops - Anjali Bhati, Application Team - Kiran Kumar",
    technicalArchitect: ""
  },
  {
    key: 12,
    serviceName: "Ewatch read IT-MBC",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "7.0.6",
  },
  {
    key: 13,
    serviceName: "Energy Audit- MBC",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "7.0.6",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "Devops - Abhishek Upadhyay, Application Team - Vishal Purohit",
    technicalArchitect: ""
  },
  {
    key: 14,
    serviceName: "EMBC",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "7.0.6",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "Devops - Anjali Bhati, Application Team - Kiran Kumar",
    technicalArchitect: "Peeyush Ameta"
  },
  {
    key: 15,
    serviceName: "GMBC",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "7.0.6",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "Devops - Anjali Bhati, Application Team - Kiran Kumar",
    technicalArchitect: "Rajinder Bedi"
  },
  {
    key: 16,
    serviceName: "MBC Insight",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ld8 & Ld9",
    version: "7.0.6",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "DevOps",
    escalationTeam: "Devops - Anjali Bhati, Application Team - Kiran Kumar",
    technicalArchitect: "Rajesh Jain"
  },
  {
    key: 17,
    serviceName: "MSEDCL",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "7.0.6",
    primaryTeam: "DevOps",
    resolverTeam: "DevOps",
    escalationTeam: "Devops - Abhishek Upadhyay, Application Team - Aayushi Soni",
    technicalArchitect: "Abhishek Sahu"
  },
  {
    key: 18,
    serviceName: "NPCL",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "7.0.6",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops",
    escalationTeam: "Devops - Anjali Bhati, Application Team - Kiran Kumar",
    technicalArchitect: ""
  },
  {
    key: 19,
    serviceName: "Adaptricity",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "7.0.6",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops, Ashish Shukla and Rahul Purohit",
    escalationTeam: "Devops - Anjali Bhati, Application Team - Amit Jain, NPD - Chenram Vijayvargiya",
    technicalArchitect: "Amit Jain NPD"
  },
  {
    key: 20,
    serviceName: "JBVNL",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "7.0.6",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops",
    escalationTeam: "Devops - Anjali Bhati, Application Team - Kiran Kumar",
    technicalArchitect: ""
  },
  {
    key: 21,
    serviceName: "LVMV",
    zabbix: "MBC DC zabbix",
    ip: "10.10.119.76",
    dataCentre: "Ctrls Noida and Mumbai",
    version: "7.0.6",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops",
    escalationTeam: "Devops - Abhishek Upadhyay, Application Team - Rajender Bedi",
    technicalArchitect: "Rajender Bedi"
  },
  {
    key: 22,
    serviceName: "L1-AIS",
    zabbix: "Liberty zabbix",
    ip: "192.168.56.43",
    dataCentre: "Ld8 & Ld9",
    version: "7.0.3",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops",
    escalationTeam: "Devops - Anjali Bhati, DBA Team - Naveen mathur",
    technicalArchitect: "Sanjay Somani"
  },
  {
    key: 23,
    serviceName: "L2-ROW",
    zabbix: "Liberty zabbix",
    ip: "192.168.56.43",
    dataCentre: "Ld8 & Ld9",
    version: "7.0.3",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops",
    escalationTeam: "Devops - Anjali Bhati, DBA Team - Naveen mathur",
    technicalArchitect: "Sanjay Somani"
  },
  {
    key: 24,
    serviceName: "L3-EUM",
    zabbix: "Liberty zabbix",
    ip: "192.168.56.43",
    dataCentre: "Ld8 & Ld9",
    version: "7.0.3",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops",
    escalationTeam: "Devops - Anjali Bhati, DBA Team - Naveen mathur",
    technicalArchitect: "Sanjay Somani"
  },
  {
    key: 25,
    serviceName: "L4-Oman",
    zabbix: "Liberty zabbix",
    ip: "192.168.56.43",
    dataCentre: "Ld8 & Ld9",
    version: "7.0.3",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Devops",
    escalationTeam: "Devops - Anjali Bhati, DBA Team - Naveen mathur",
    technicalArchitect: "Sanjay Somani"
  },
  {
    key: 26,
    serviceName: "Muti Fuel",
    zabbix: "Liberty zabbix",
    ip: "192.168.56.43",
    dataCentre: "Ld8 & Ld9",
    version: "7.0.3",
  },
  {
    key: 27,
    serviceName: "Sahaj Liberty 150",
    zabbix: "Liberty zabbix",
    ip: "192.168.56.43",
    dataCentre: "Ld8 & Ld9",
    version: "7.0.3",
  },
  {
    key: 28,
    serviceName: "Australia P2P-Smart Metering (S2-WSE, Bravo and SFE)",
    zabbix: "Australia zabbix",
    ip: "172.16.192.203",
    dataCentre: "Melbourne and Sydney",
    version: "7.0.6",
    primaryTeam: "Smart Support-OZ",
    resolverTeam: "Smart Support-OZ",
    escalationTeam: "WSE - Sontosh Prajapati, SFE - Gaurav Negi, Bravo - Devops",
    technicalArchitect: "Technical Architect: WSE - Dharam Menaria, SFE - Lalit Sharma, Bravo - Deepesh Goswami"
  },
  {
    key: 29,
    serviceName: "Bravo MDM Services",
    zabbix: "Australia zabbix",
    ip: "172.16.192.203",
    dataCentre: "Melbourne and Sydney",
    version: "7.0.6",
  },
  {
    key: 30,
    serviceName: "Republic of Ireland - S3WSE",
    zabbix: "S3 zabbix",
    ip: "172.16.201.80",
    dataCentre: "Ld8",
    version: "6.2.9",
    primaryTeam: "Smart Support-GB",
    resolverTeam: "Smart Support-GB",
    escalationTeam: "WSE - Dharam Menaria and UK NOC, SFE - Sunil Sharma",
    technicalArchitect: "WSE - Dharam Menaria, SFE - Lalit Sharma"
  },
  {
    key: 31,
    serviceName: "GBSM (S1-WSE and SFE)",
    zabbix: "SFE zabbix",
    ip: "172.16.150.107",
    dataCentre: "Ld8",
    version: "6.0.35",
    primaryTeam: "Smart Support-GB",
    resolverTeam: "Smart Support-GB",
    escalationTeam: "WSE - Dharam Menaria and UK NOC, SFE - Sunil Sharma, Lalit Sharma",
    technicalArchitect: "WSE - Dharam Menaria, SFE - Lalit Sharma"
  },
  {
    key: 32,
    serviceName: "Monitor IT",
    zabbix: "MonitorIT zabbix",
    ip: "172.22.231.130",
    dataCentre: "",
    version: "6.2.9",
    primaryTeam: "Liberty Helpdesk",
    resolverTeam: "Data Services",
    escalationTeam: "Devops - , Application Team - Mukesh Kumar",
    technicalArchitect: ""
  },
  {
    key: 33,
    serviceName: "DCC-SMETS1",
    zabbix: "DCC Zabbix",
    ip: "",
    dataCentre: "LD8 & LD9",
    version: "7.2.0",
    primaryTeam: "S1SP Helpdesk",
    resolverTeam: "NOC UK Team",
    escalationTeam: "Application Team - Niranjan Ameta",
    technicalArchitect: "Niranjan Ameta"
  },
  {
    key: 34,
    serviceName: "Service ERP",
    zabbix: "",
    ip: "",
    dataCentre: "",
    version: "",
  },
  {
    key: 35,
    serviceName: "JVVNL",
    zabbix: "",
    ip: "",
    dataCentre: "",
    version: "",
    primaryTeam: "Data services",
    resolverTeam: "Data services",
    escalationTeam: "DevOps - Abhishek Upadhyay, Application Team - Bhargav Joshi",
    technicalArchitect: ""
  },
];
